# Generated by Django 6.0.5 on 2026-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeammatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('badminton', 'Бадминтон'), ('hockey', 'Хоккей'), ('other', 'Другое')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('required_level', models.CharField(choices=[('any', 'Любой'), ('beginner', 'Новичок'), ('amateur', 'Любитель'), ('semi_pro', 'Полупрофессионал'), ('pro', 'Профессионал')], default='any', max_length=20)),
                ('players_needed', models.PositiveSmallIntegerField(default=1)),
                ('play_date', models.DateField(blank=True, null=True)),
                ('play_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeammateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
