# Generated by Django 6.0.5 on 2026-05-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teammates', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammatepost',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammate_posts', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='teammaterequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammaterequest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teammates.teammatepost'),
        ),
        migrations.AlterUniqueTogether(
            name='teammaterequest',
            unique_together={('post', 'applicant')},
        ),
    ]
